#!/usr/bin/env python3
"""Turn .work/skills.json into js/skills.js, and refuse to write a broken ladder.

The skill graph is the spine of this app: it drives the unlock order on the map,
the prerequisite mix in the daily deck, and every range assertion in
check_generators.py. A cycle or a forward reference in it is not a cosmetic
problem — it is a skill a child can never reach, or a deck that recommends
something before its prerequisite exists.

So this is a gate, not a converter. It rejects; it does not repair.

  .venv-tts/bin/python tools/build_skills.py
"""
import json
import os
import sys
import tempfile

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
_WORK = os.path.join(ROOT, '.work', 'tmp')
os.makedirs(_WORK, exist_ok=True)
tempfile.tempdir = _WORK          # never the system temp dir
os.environ.setdefault('HF_HOME', os.path.join(ROOT, '.work', 'hf'))

SRC = os.path.join(ROOT, '.work', 'skills.json')
OUT = os.path.join(ROOT, 'js', 'skills.js')

REQUIRED = {'id', 'g', 's', 'name', 'range', 'pre', 'mode'}
MODES = {'gen', 'svg'}


def check(data):
    """Every way this file can be wrong, checked before anything is written."""
    problems = []
    strands = data.get('strands') or {}
    skills = data.get('skills') or []
    if not strands or not skills:
        return ['skills.json is empty or missing its top-level keys']

    ids = [s.get('id') for s in skills]
    seen = set()
    for i in ids:
        # Ids are load-bearing: every progress record keys on one. A duplicate
        # silently merges two skills' histories.
        if i in seen:
            problems.append(f'duplicate id {i!r}')
        seen.add(i)

    by = {s['id']: s for s in skills if 'id' in s}
    for s in skills:
        sid = s.get('id', '<no id>')
        missing = REQUIRED - set(s)
        if missing:
            problems.append(f'{sid}: missing {sorted(missing)}')
            continue
        if s['s'] not in strands:
            problems.append(f'{sid}: unknown strand {s["s"]!r}')
        if s['mode'] not in MODES:
            problems.append(f'{sid}: mode must be one of {sorted(MODES)}')
        if not 1 <= s['g'] <= 6:
            problems.append(f'{sid}: grade {s["g"]} outside 1-6')
        if not str(s['range']).strip():
            problems.append(f'{sid}: empty range — check_generators.py has '
                            'nothing to assert against')
        for p in s['pre']:
            if p not in by:
                problems.append(f'{sid}: prerequisite {p!r} does not exist')
            elif by[p]['g'] > s['g']:
                problems.append(f'{sid} (grade {s["g"]}) requires {p} from the '
                                f'later grade {by[p]["g"]}')

    # Cycles. A child can never reach a skill inside one.
    WHITE, GREY, BLACK = 0, 1, 2
    colour = {i: WHITE for i in by}

    def visit(i, stack):
        if colour[i] == GREY:
            problems.append('cycle: ' + ' -> '.join(stack[stack.index(i):] + [i]))
            return
        if colour[i] == BLACK:
            return
        colour[i] = GREY
        for p in by[i]['pre']:
            if p in by:
                visit(p, stack + [i])
        colour[i] = BLACK

    for i in list(by):
        visit(i, [])
    return problems


def depth(by, i, memo):
    if i in memo:
        return memo[i]
    memo[i] = 1 + max([depth(by, p, memo) for p in by[i]['pre'] if p in by] or [0])
    return memo[i]


def main():
    if not os.path.exists(SRC):
        print(f'missing {os.path.relpath(SRC, ROOT)}')
        return 1
    with open(SRC, encoding='utf-8') as f:
        data = json.load(f)

    problems = check(data)
    if problems:
        # Report everything, at the end, after every check has contributed.
        # Printing partway through is how two rejected items vanish unnoticed.
        for p in problems[:40]:
            print('  ' + p)
        print(f'\n{len(problems)} problem(s) — js/skills.js NOT written')
        return 1

    skills = data['skills']
    by = {s['id']: s for s in skills}
    memo = {}
    for s in skills:
        s['depth'] = depth(by, s['id'], memo)

    # Precomputed so the app never walks the graph at render time.
    kids = {s['id']: [] for s in skills}
    for s in skills:
        for p in s['pre']:
            kids[p].append(s['id'])
    for s in skills:
        s['next'] = kids[s['id']]

    order = ['id', 'g', 's', 'name', 'range', 'pre', 'next', 'mode', 'depth']
    rows = [{k: s[k] for k in order} for s in skills]

    header = (
        '// Math Lab — the skill graph. Generated by tools/build_skills.py.\n'
        '// DO NOT HAND-EDIT: edit .work/skills.json and rerun the builder, or\n'
        '// the next build silently reverts your change.\n'
        f'//\n'
        f'// {len(rows)} skills across {len(data["strands"])} strands, grades 1-6.\n'
        f'// Deepest prerequisite chain: {max(memo.values())}.\n'
        '// The builder refuses to write this file if the graph has a cycle, a\n'
        '// prerequisite that does not exist, or a skill that depends on a later\n'
        '// grade.\n\n'
    )
    body = ('const STRANDS = ' + json.dumps(data['strands'], ensure_ascii=False) + ';\n\n'
            + 'const SKILLS = ' + json.dumps(rows, ensure_ascii=False) + ';\n\n'
            + 'const SKILL = Object.fromEntries(SKILLS.map(s => [s.id, s]));\n')

    with open(OUT, 'w', encoding='utf-8') as f:
        f.write(header + body)

    per_grade = {}
    for s in rows:
        per_grade[s['g']] = per_grade.get(s['g'], 0) + 1
    print(f'{len(rows)} skills -> {os.path.relpath(OUT, ROOT)}')
    print('  per grade:', dict(sorted(per_grade.items())))
    print('  deepest chain:', max(memo.values()))
    return 0


if __name__ == '__main__':
    sys.exit(main())
